# Generated by Django 3.2.4 on 2023-01-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterials',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=20)),
                ('date', models.DateField(db_column='Date')),
                ('time', models.TimeField(db_column='Time')),
                ('study_material', models.CharField(db_column='Study_material', max_length=30)),
            ],
            options={
                'db_table': 'study_materials',
                'managed': False,
            },
        ),
    ]
