# Generated by Django 3.2.4 on 2023-01-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_id', models.IntegerField()),
                ('time_table', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'time_table',
                'managed': False,
            },
        ),
    ]
