# Generated by Django 3.2.4 on 2023-01-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('roll_no', models.IntegerField()),
                ('age', models.IntegerField(db_column='Age')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
